# Generated by Django 5.2.4 on 2025-07-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='system_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
