# Generated by Django 5.2.4 on 2025-07-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_integration_system_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='system_text',
        ),
    ]
