# Generated by Django 5.2.4 on 2025-07-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_integration_system_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='system_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
