# Generated by Django 5.2.4 on 2025-07-25 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FileProcessing', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='FileProcessing.document'),
        ),
        migrations.AddField(
            model_name='embedding',
            name='chunk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='FileProcessing.chunk'),
        ),
    ]
